"""
AI Output Validation Schemas

These Pydantic models enforce structure on every AI-generated output.
If the model returns malformed, incomplete, or invalid data, these
schemas reject it immediately — triggering an automatic retry.

This is the core reliability layer of the pipeline.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Literal


# ──────────────────────────────────────────────
# Stage 2: Requirement Extraction Output
# ──────────────────────────────────────────────
class ExtractedRequirement(BaseModel):
    """A single testable requirement extracted from the document."""

    requirement_text: str = Field(
        min_length=10,
        max_length=1000,
        description="Clear, concise description of one testable behavior",
    )
    category: Literal["functional", "ui", "api", "security", "performance", "data"] = Field(
        description="Requirement category",
    )
    priority: Literal["high", "medium", "low"] = Field(
        description="Relative priority of this requirement",
    )

    @field_validator("requirement_text")
    @classmethod
    def requirement_not_vague(cls, v: str) -> str:
        """Reject obviously vague or non-testable requirements."""
        vague_phrases = ["tbd", "to be determined", "etc", "and more", "various"]
        lower = v.lower().strip()
        for phrase in vague_phrases:
            if lower.endswith(phrase) or lower == phrase:
                raise ValueError(f"Requirement is too vague (ends with '{phrase}')")
        return v


class RequirementExtractionResult(BaseModel):
    """Validated output from the requirement extraction AI call."""

    requirements: list[ExtractedRequirement] = Field(
        min_length=1,
        description="List of extracted requirements (at least 1)",
    )


# ──────────────────────────────────────────────
# Stage 3: Test Case Generation Output
# ──────────────────────────────────────────────
class GeneratedTestCase(BaseModel):
    """A single test case generated by the AI."""

    title: str = Field(
        min_length=5,
        max_length=500,
        description="Short, descriptive test case title",
    )
    description: str = Field(
        min_length=10,
        description="What this test verifies",
    )
    test_type: Literal["functional", "edge_case", "negative"] = Field(
        description="Category of this test case",
    )
    preconditions: str = Field(
        default="None",
        description="Setup or state required before executing this test",
    )
    steps: list[str] = Field(
        min_length=1,
        description="Ordered list of actionable test steps",
    )
    expected_result: str = Field(
        min_length=10,
        description="The verifiable expected outcome",
    )
    priority: Literal["critical", "high", "medium", "low"] = Field(
        description="Test case priority",
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Relevant tags (e.g., 'auth', 'validation', 'api')",
    )

    @field_validator("steps")
    @classmethod
    def steps_must_be_actionable(cls, v: list[str]) -> list[str]:
        """Reject empty or placeholder steps."""
        cleaned = [s.strip() for s in v if s.strip()]
        if len(cleaned) == 0:
            raise ValueError("Steps list cannot be empty after cleaning")
        return cleaned

    @field_validator("tags")
    @classmethod
    def tags_lowercase(cls, v: list[str]) -> list[str]:
        """Normalize tags to lowercase."""
        return [t.strip().lower() for t in v if t.strip()]


class TestGenerationResult(BaseModel):
    """Validated output from the test case generation AI call."""

    test_cases: list[GeneratedTestCase] = Field(
        min_length=1,
        description="List of generated test cases (at least 1)",
    )
